### ISSUE TITLE
can't iterate

### ISSUE THREAD

**Issue by Love-Studyyy** [sudecki30/labels#1]
Hi, can you help me please?   

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Segment\envs\trans\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "d:\labels-master\png_to_json.py", line 149, in image_to_json
    segmentations,areas,bboxs = create_sub_mask_annotation(mask, image_id, category_id, annotation_id, is_crowd)
  File "d:\labels-master\png_to_json.py", line 53, in create_sub_mask_annotation
    contour = np.vstack(contour).squeeze()
  File "<__array_function__ internals>", line 6, in vstack
TypeError: dispatcher for __array_function__ did not return an iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:/labels-master/png_to_json.py", line 251, in <module>
    for _ in tqdm.tqdm(pool.imap( image_to_json_partial, range(l)), total=l):
  File "D:\Segment\envs\trans\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "D:\Segment\envs\trans\lib\multiprocessing\pool.py", line 736, in next
    raise value
TypeError: dispatcher for __array_function__ did not return an iterable

-----How can I solve it?

**Comment by sudecki30** [comment]
Hi, I have correct the code to work with actual package version

**Comment by Love-Studyyy** [comment]
It is successful!!!!!!!!!
My gratitude to you for all you have done!!!!!!!!!
